name: Export Cloudflare Gateway Lists

on:
  schedule:
    - cron: '0 23 * * 0'  # 23:00 Chủ nhật giờ VN = 16:00 UTC
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install requests

      - name: Export all lists from Cloudflare Gateway
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          mkdir -p logs
          python export_blocklist.py

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add my-blocklist.txt logs/list_details.log
          git commit -m "Weekly update of blocklist and log from Cloudflare Gateway" || echo "No changes to commit"
          git push
