name: Export Lists to my-blocklist.txt

on:
  schedule:
    - cron: '30 23 * * 0'  # Chủ nhật 23:00 (GMT+7)
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    # Cho phép ghi vào repo bằng GITHUB_TOKEN
    permissions:
      contents: write

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 📦 Install dependencies
        run: pip install requests

      - name: 🚀 Run export script
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: python export_blocklist.py

      - name: 💾 Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add my-blocklist.txt logs/list_details.log || true
          git commit -m "🔄 Update my-blocklist.txt and logs [auto]" || echo "No changes to commit"
          git push origin main
