name: Merge Blocklists

on:
  workflow_run:
    workflows: ["Export Lists"]
    types:
      - completed
  workflow_dispatch:

jobs:
  merge-blocklists:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Run merge script
        run: python merge_hosts.py
        env:
          NGUON_URLS: ${{ vars.NGUON_URLS }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add merged_blocklist.txt
          git commit -m "🔄 Auto-merge blocklists [triggered]" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
